apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: product-saga
spec:
  template:
    spec:
      containers:
        - image: dev.local/product-saga
---
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source-product-orders
spec:
  bootstrapServers:
    - my-cluster-kafka-bootstrap.kafka:9092
  topics:
    - order-events
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: product-saga
    uri: /products/reserve